### ISSUE TITLE
Coredump while running forjj maintain or getting help

### ISSUE THREAD

**Issue by clarsonneur** [forj-oss/forjj#54]
In or out a forj-infra repository, I got the following coredump issue.

I current do not know why we are getting this issue.
Seems related to the workspace object not loaded in cli module.

```bash
forjj help
branch master, build_date 2017-08-04_15:01:22_+0200, build_commit 50b2e6349faf13fd5a9c091af40c42c36c6a7136, build_tag false.
2017/08/05 14:12:08 Organization : 'forjj-test'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x411be3]

goroutine 1 [running]:
panic(0x7f58e0, 0xc42000e140)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
main.(*Forj).read_driver(0xa66f40, 0xc420136650, 0x6, 0xc4201378f0, 0xc42011b9b0)
        /go/src/forjj/drivers_options.go:72 +0xa3
main.(*Forj).load_driver_options(0xa66f40, 0xc420136650, 0x6, 0x1, 0x1)
        /go/src/forjj/drivers_options.go:19 +0x43
main.(*Forj).ParseContext(0xa66f40, 0xc4200b40c0, 0x0, 0x0, 0xc420011ec0, 0xc4200f0340, 0xa62a10)
        /go/src/forjj/cli_context.go:112 +0x771
main.(*Forj).ParseContext-fm(0xc4200b40c0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/forjj/app.go:183 +0x48
forjj/vendor/github.com/forj-oss/forjj-modules/cli.(*ForjCli).contextHook(0xc4200b40c0, 0x0, 0x0, 0xc420036868, 0x0, 0x0)
        /go/src/forjj/vendor/github.com/forj-oss/forjj-modules/cli/forjj-context.go:149 +0x1f8
forjj/vendor/github.com/forj-oss/forjj-modules/cli.(*ForjCli).loadContext(0xc4200b40c0, 0xc42000a510, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
        /go/src/forjj/vendor/github.com/forj-oss/forjj-modules/cli/forjj-context.go:56 +0x1ab
forjj/vendor/github.com/forj-oss/forjj-modules/cli.(*ForjCli).Parse(0xc4200b40c0, 0xc42000a510, 0x1, 0x1, 0x0, 0x0, 0x7d31a0, 0xc4200910b8, 0x8ade30, 0x7fd7215f2000)
        /go/src/forjj/vendor/github.com/forj-oss/forjj-modules/cli/forj-cli.go:61 +0x6e
main.main()
        /go/src/forjj/forjj.go:35 +0x106
```

**Comment by clarsonneur** [comment]
After the coredump fix, the issue is still there, but with the following issue:
```bash
~/tmp/forjj-test/ $ forjj help
branch master, build_date 2017-08-04_15:01:22_+0200, build_commit 50b2e6349faf13fd5a9c091af40c42c36c6a7136, build_tag false.
2017/08/05 14:22:03 Organization : 'forjj-test'
forjj: error: Contribs repository url issue: Unable to find Object 'workspace', try --help
```

if we are outside the infra repository, we have: 
```bash
~/tmp)
└─> forjj help
branch master, build_date 2017-08-04_15:01:22_+0200, build_commit 50b2e6349faf13fd5a9c091af40c42c36c6a7136, build_tag false.
forjj: error: Forjfile not loaded. stat /home/larsonsh/tmp/Forjfile: no such file or directory, try --help
```

And at the end, we do not get the help.

maintain is in the same trouble.

**Comment by clarsonneur** [comment]
Note that `forjj help` will never printout the help message. if we want to get help, we need to do `forjj --help`

When we ask to get help with --help, we do not have this issue.

This said, doing a `forj help` outside an infra repository, should not return an issue saying the Forjfile is not loaded and exit. We expect to have simply the help with an error saying help is not a valid command

If we are in a infra repo, we should have the same kind of error.
